version: "3.8"
services:
  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - 27020:27017
    networks:
      - docai_network

  backend:
    build:
      context: .
    image: docai_backend:latest
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - docai_network

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongodb
    restart: always
    networks:
      - docai_network

networks:
  docai_network:
    external: false
